; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = MainNode
[env:MainNode]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+

lib_deps =
    sandeepmistry/LoRa
    bblanchon/ArduinoJson
    witnessmenow/UniversalTelegramBot
    adafruit/RTClib
    SPI
    Wire
build_src_filter =
    +<*>
    -<LoRaNode.cpp>
    

[env:LoRaNode]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+

lib_deps =
    sandeepmistry/LoRa
    bblanchon/ArduinoJson
    SPI
    Wire
build_src_filter =
    +<*>
    -<main.cpp>
    -<TTC_SSR.ino>